### ISSUE TITLE
Fatal errors on activating new version (1.3).

### ISSUE THREAD

**Issue by aukondk** [marinsagovac/woocommerce-tcom-payway#6]
Notice: Undefined offset: 0 in /var/www/html/wp-content/plugins/woo-multi-currency/includes/data.php on line 677

Notice: Undefined offset: 0 in /var/www/html/wp-content/plugins/woo-multi-currency/includes/data.php on line 679

Notice: Undefined variable: order in /var/www/html/wp-content/plugins/woocommerce-tcom-payway-1.3/classes/class-wc-tpayway.php on line 20

Fatal error: Uncaught Error: Call to a member function get_page_permastruct() on null in /var/www/html/wp-includes/link-template.php:376 Stack trace: #0 /var/www/html/wp-includes/link-template.php(338): _get_page_link() #1 /var/www/html/wp-includes/link-template.php(146): get_page_link() #2 /var/www/html/wp-content/plugins/woocommerce/includes/wc-page-functions.php(67): get_permalink() #3 /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1320): wc_get_page_permalink() #4 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php(228): wc_get_checkout_url() #5 /var/www/html/wp-content/plugins/woocommerce-tcom-payway-1.3/classes/class-wc-tpayway.php(20): WC_Payment_Gateway->get_return_url() #6 /var/www/html/wp-content/plugins/woocommerce-tcom-payway-1.3/tcom-payway-woocommerce.php(40): WC_TPAYWAY->__construct() #7 /var/www/html/wp-includes/class-wp-hook.php(287): woocommerce_tpayway_gateway() #8 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_fi in /var/www/html/wp-includes/link-template.php on line 376

Removing Woo Multi Currency makes no difference.

**Comment by aukondk** [comment]
Tracked it down. Spelling fixes to the settings names had not been changed in the database (responce_url_sucess and responce_url_fail). I changed them manually and it works.
